### PR TITLE
Optimize tof functions

### PR DESCRIPTION
**Pull request by carmenromo**
I have optimized the tof functions that add the electronics effect for the sipm response. The speed has been increased by two orders of magnitude!

### CODE REVIEW

**Comment by paolafer** [comment]
Yeah! Death to loops!

**Comment by paolafer** [comment]
A question: the `translate_charge_matrix_to_wf_df` function returns the dataframe that is then used for analysis, right? Do the sensor IDs of this dataframe start from 0 or do theyhave their original ID?

**Comment by carmenromo** [comment]
> A question: the `translate_charge_matrix_to_wf_df` function returns the dataframe that is then used for analysis, right? Do the sensor IDs of this dataframe start from 0 or do they have their original ID?

They have their original ID, yes

**Comment by carmenromo** [comment]
This PR has been cleaned too and it is ready to review

**Comment by paolafer** [comment]
@viherbos, do you have time to have a look at this PR?

**Comment by viherbos** [comment]
Hi all. The code looks beautiful indeed, Carmen. The technique used for convolution computation is very smart. I guess it saves a lot of time (I wish I'd have come up with that myself ;-)
Just a comment about the spe_dist function: I think it would be desirable to include the time constants as parameters for future usage with different SiPMs. Maybe a set of configuration parameters could be stored in a .json file close to the database. 
Congratulations!

**Comment by viherbos** [comment]
Hi all. The code looks beautiful indeed, Carmen. The technique used for convolution computation is very smart. I guess it saves a lot of time (I wish I'd have come up with that myself ;-)
Just a comment about the spe_dist function: I think it would be desirable to include the time constants as parameters for future usage with different SiPMs. Maybe a set of configuration parameters could be stored in a .json file close to the database. 
Congratulations!

**Pull request merged**
