### PR TITLE
CRC functions

### PR DESCRIPTION
**Pull request by paolafer**
This PR adds functions to calculate the Contrast Recovery Coefficient, to compare the resolution of different images.

### CODE REVIEW

**Comment by paolafer** [comment]
According to Marija's slides, test functions should start with `test_`, but test files can be either `test_` or `_test`. Here I've followed IC's convention.
I'm going to add a CRC function also for 3D. images, as discussed yesterday.

**Comment by paolafer** [comment]
@jerenner, have a look at the latest changes and, if you're happy with the new 3d functions and the change in the definition of crc for cold spheres, I'll proceed to merge.

**Comment by jerenner** [comment]
Ok - the code looks good to me!  I have seen (https://doi.org/10.1088/1361-6560/aaf9b9), for the definition of CRC_hot, 

CRC_hot = (signal / bckg - 1) / (max_intensity - 1)

I don't remember where the one we are using came from - is it also often defined without the -1s?

**Comment by paolafer** [comment]
I was following https://ieeexplore.ieee.org/document/6704829. It doesn't use (- 1), what is the rationale behind it? I think that it doesn't matter much which definition we use, as long as we're consistent.

**Comment by jerenner** [comment]
I have not seen an explanation for the -1, but it may be so that the CRC is "undefined" if the signal intensity is defined to be the same as the background intensity.  In fact, the formula I had written previously was not right, it should be:

CRC_hot = (signal/bckg - 1) / (alpha - 1)

where alpha is the true signal/background ratio (in our case 4/1), not the max intensity. If we also made our signal intensity = 1, then the true signal/background would be 1, and with our current definition, the CRC would most likely be near 1, even though there technically is no "signal" (since we've defined it to be = 1, the same as background).

Since in our case the signal (4) is significantly different than the background (1), I think as long as we are using a consistent, sensible definition, it should be fine. What confuses me now is that the paper in which they use the formula with the -1 cites formula from the paper (Westerwoudt et al, 2014) in the link you just sent!

**Comment by paolafer** [comment]
I see your point, it makes sense! I would then use the -1.

**Pull request merged**
