### PR TITLE
Adapt ANTEA to updated hdf5 scheme in nexus

### PR DESCRIPTION
**Pull request by paolafer**
This PR changes a few things to adapt the code to the most recent format of nexus output files, namely a change in the name of two tables and a particle property.

### CODE REVIEW

**Comment by carmenromo** [comment]
I have noticed that in some ANTEA files we use the word `waveforms` to refer the `sns_response` dataframe. Do you think it's worth changing those names as well?

**Comment by paolafer** [comment]
Yeah, that would make more sense, I will change that, too.

**Comment by paolafer** [comment]
The problem with this changes is that we should replace the files of some of the tests, too. Alternatively, we could just rewrite the test files and change `waveforms` for `sns_response`. It could may be the easiest way, since the content of the tables will be just copied. We should check if we use the `particle_name` field in the tests, too.

**Comment by carmenromo** [comment]
This PR adapts the code to the latest changes in NEXUS: `waveforms` has been replaced with `sns_response` in most of the cases and the column `name` of the `particles` table has been replaced with `particle_name`. Tests files have been modificated as well except the one that still uses tables. Everything works, so I approve!

**Pull request merged**
