### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by jerenner**
Initial version of documentation for ANTEA. This serves as a place to write descriptions on how to run code in ANTEA as well as HTML documentation of the code itself. It is built on sphinx, which can convert docstrings into html documentation, so in principle keeping the documentation up-to-date should require little effort, provided we continue to comment with docstrings. The procedure for updating the documentation is described on the front page - in summary:

- adding/updating code in existing files that are already included in the documentation should require only rebuilding with sphinx
- adding a new file should only require adding the appropriate "automodule" pointing to the file in the documentation source
- additional documentation source files can be added if necessary as the code expands
- descriptions, examples, etc. that are not in docstrings can be added manually to the source files of the documentation, which are written in [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText)

Note that once added to ANTEA, the documentation can be hosted via GitHub pages by [enabling it in the "Settings" tab](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

### CODE REVIEW

**Comment by jerenner** [comment]
Once the "improve safeness" pull request is merged, this can be rebased on top of it and the documentation updated before merging

**Comment by jerenner** [comment]
Alternatively, we could try to set this up through [Read the Docs](https://docs.readthedocs.io/en/stable/index.html), and it will build the documentation automatically (we won't have to run `make html` to apply changes) as files are pushed to the repository.

**Comment by paolafer** [comment]
Here I don't have a strong opinion, which method do you think it is the easiest to maintain?

**Comment by jerenner** [comment]
I think the Read the Docs method would be easiest to maintain, as we would only need to worry about maintaining the source files, and they would only need to be updated when a new Python file is added or when documentation is added outside of docstrings. I will try to get this working on my local repository and then see if we can get it working for nextic/ANTEA

**Comment by jerenner** [comment]
Actually I think we can do the build of the documentation through Travis, and that may be easiest since we are already using it.  We would have to update the .travis.yml file

**Pull request merged**
