### PR TITLE
Adds interface to CPP-based reconstruction

### PR DESCRIPTION
**Pull request by jerenner**
Python interface to C++ reconstruction functions

### CODE REVIEW

**Comment by paolafer** [comment]
Do you think that there could be a test or two for this code?

**Comment by jerenner** [comment]
Ok - working on this

**Comment by paolafer** [comment]
I reckon that the test is failing...

**Comment by jerenner** [comment]
The test should pass locally if the .so library is installed in the location $ANTEADIR/../anteacpp/libPETALO.so. Since the test is using code that we have not yet uploaded to GitHub, it will not pass on Travis.

**Comment by paolafer** [comment]
Ok! This PR adds a useful interface to run reconstruction functions within another code, still not public. A test has been added,  which is supposed to be run locally, where that code is available. I approve this PR.

**Pull request merged**
