### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by carmenromo**
This PR adds the `__init__` file needed for the tests files in the elec directory, changes how is imported `tof_functions` in `tof_functions_test`, and fixes an error in the function `spe_dist`. This change in the function forced to split the corresponding test in two and to fix the `convolve_tof` test.

### CODE REVIEW

**Comment by paolafer** [comment]
Why did you change the behaviour in case of alpha == beta?

**Comment by paolafer** [comment]
Also, tests are failing.

**Comment by carmenromo** [comment]
> Why did you change the behaviour in case of alpha == beta?

The tests was failing previously because if alpha == beta the denominator in the equation was zero

**Comment by carmenromo** [comment]
> Also, tests are failing.

Yes, I have seen it, however in my local they weren't. But I am looking at this

**Comment by carmenromo** [comment]
> > Why did you change the behaviour in case of alpha == beta?
> 
> The tests was failing previously because if alpha == beta the denominator in the equation was zero

And hypothesis always finds a decimal which make two numbers practically equals...

**Comment by carmenromo** [comment]
I will add the changes in the other function and corresponding test in another PR, so this one can be approved

**Comment by paolafer** [comment]
Ok! I approve this PR, then.

**Pull request merged**
